export const GET_COCKTAILS_LOADING = 'GET_COCKTAILS_LOADING';
export const GET_COCKTAILS = 'GET_COCKTAILS';
export const GET_COCKTAILS_ERRORS = 'GET_COCKTAILS_ERRORS';
export const GET_COCKTAIL = 'GET_COCKTAIL';
export const SEARCH_FILTER = "SEARCH_FILTER";
export const GET_LIST_FILTERED = "GET_LIST_FILTERED";
export const GET_RANDOM_COCKTAIL = "GET_RANDOM_COCKTAIL";